#!/bin/bash

bin="/var/packages/ffmpeg/target/bin/ffmpeg"

args=()
while [[ $# -gt 0 ]]
do
case "$1" in
    -vf)
       shift
       vf=$(echo "$1" | sed -e 's/format=nv12.*scale_vaapi/scale_vaapi/g' -e 's/$/:format=nv12,hwupload,setsar=sar=1/')
       args+=("-vf" "$vf")
       ;;
    *)
       args+=("$1")
       ;;
esac
shift
done

set -- "${args[@]}"

nohup $bin "$@" </dev/null &
running=`echo $!`

# Kill previous instances of ffmpeg
for pid in `pidof ffmpeg`
do
   [ $pid -ne $$ -a $pid -ne $running ] && kill $pid
done
